import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
});

const albra = localFont({
  src: "../public/fonts/Albra-Light.woff",
  variable: "--font-albra",
  weight: "300",
});

const helveticaNow = localFont({
  src: "../public/fonts/HelveticaNowDisplay-Regular.woff",
  variable: "--font-helvetica-now",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable}  ${albra.variable} ${helveticaNow.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
